Revert "try moving pandokia/helpers/pytest_plugin.py to utils/helpers/pytest_plugin.py to see if it helps with pytest failures with pytest_plugin.py during teardown AttributeError: 'data_item' object has no attribute 'timeout'"
This reverts commit 5a1582c201edcf76ed42d442a0a0d2cba9d40228.